using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ArktinMonitor.Data.Models;

namespace ArktinMonitor.ServiceApp.Services
{
    internal static class SitesBlocker
    {
        private static readonly string HostsFileLocation = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), @"drivers\etc\hosts");
        private static readonly string FakeHostsFileLocation = Path.Combine(Settings.LocalStoragePath, "hosts");

        public static void BlockSites(List<BlockedSiteLocal> blockedSites)
        {
            ClearHostsFile();

            var blockedEntries = new StringBuilder();

            var hostsFileContent = File.ReadAllText(HostsFileLocation);

            foreach (var blockedSite in blockedSites)
            {
                blockedEntries.AppendLine($"127.0.0.1 {blockedSite.UrlAddress} #Autogenerated by ArktinMonitor");
            }
            File.WriteAllText(HostsFileLocation, hostsFileContent + Environment.NewLine + blockedEntries);

        }

        public static void ClearHostsFile()
        {
            var hostsFileContent = new StringBuilder();

            var rawList = File.ReadAllLines(HostsFileLocation).ToList();
            foreach (var item in rawList)
            {
                if (item.Contains("#Autogenerated by ArktinMonitor")) continue;
                hostsFileContent.Append(item + Environment.NewLine);
            }
            File.WriteAllText(HostsFileLocation, hostsFileContent.ToString().TrimEnd());
        }
    }
}
